/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package gestion_produit_crud.api;

import gestion_produit_crud.dto.LoginRequestDTO;
import gestion_produit_crud.dto.LoginResponseDTO;
import gestion_produit_crud.dto.UtilisateurDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-16T00:19:24.782253500Z[Atlantic/Reykjavik]", comments = "Generator version: 7.19.0")
@Validated
@Tag(name = "Auth", description = "the Auth API")
public interface AuthApi {

    String PATH_LOGIN = "/auth/login";
    /**
     * POST /auth/login : Authentification utilisateur
     *
     * @param loginRequestDTO  (required)
     * @return Connexion réussie (status code 200)
     */
    @Operation(
        operationId = "login",
        summary = "Authentification utilisateur",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Connexion réussie", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<LoginResponseDTO> _login(
        @Parameter(name = "LoginRequestDTO", description = "", required = true) @Valid @RequestBody LoginRequestDTO loginRequestDTO
    );


    String PATH_REGISTER_USER = "/auth/registrer";
    /**
     * POST /auth/registrer : Inscription de l&#39;utilisateur
     *
     * @param utilisateurDTO  (required)
     * @return Utilisateur créé (status code 201)
     */
    @Operation(
        operationId = "registerUser",
        summary = "Inscription de l'utilisateur",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Utilisateur créé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UtilisateurDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_REGISTER_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<UtilisateurDTO> _registerUser(
        @Parameter(name = "UtilisateurDTO", description = "", required = true) @Valid @RequestBody UtilisateurDTO utilisateurDTO
    );

}
