/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package gestion_produit_crud.api;

import gestion_produit_crud.dto.CategorieDTO;
import gestion_produit_crud.dto.CategorieUpdateDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-16T00:19:24.782253500Z[Atlantic/Reykjavik]", comments = "Generator version: 7.19.0")
@Validated
@Tag(name = "Categorie", description = "the Categorie API")
public interface CategoriesApi {

    String PATH_AFFICHE_CATEGORIE_PAR_ID = "/categories/{id}";
    /**
     * GET /categories/{id} : Détail d’une categorie
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "afficheCategorieParId",
        summary = "Détail d’une categorie",
        tags = { "Categorie" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategorieDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CategoriesApi.PATH_AFFICHE_CATEGORIE_PAR_ID,
        produces = { "application/json" }
    )
    ResponseEntity<CategorieDTO> _afficheCategorieParId(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    String PATH_AJOUT_CATEGORIE = "/categories";
    /**
     * POST /categories : Créer une categorie
     *
     * @param categorieDTO  (required)
     * @return categorie créé (status code 201)
     */
    @Operation(
        operationId = "ajoutCategorie",
        summary = "Créer une categorie",
        tags = { "Categorie" },
        responses = {
            @ApiResponse(responseCode = "201", description = "categorie créé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategorieDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CategoriesApi.PATH_AJOUT_CATEGORIE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CategorieDTO> _ajoutCategorie(
        @Parameter(name = "CategorieDTO", description = "", required = true) @Valid @RequestBody CategorieDTO categorieDTO
    );


    String PATH_LIST_CATEGORIES = "/categories";
    /**
     * GET /categories : Liste des catégories
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "listCategories",
        summary = "Liste des catégories",
        tags = { "Categorie" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CategorieDTO.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CategoriesApi.PATH_LIST_CATEGORIES,
        produces = { "application/json" }
    )
    ResponseEntity<List<CategorieDTO>> _listCategories(
        
    );


    String PATH_MODIFIER_CATEGORIE = "/categories/{id}";
    /**
     * PUT /categories/{id} : Modifier une categorie
     *
     * @param id  (required)
     * @param categorieUpdateDTO  (required)
     * @return categorie modifié (status code 200)
     */
    @Operation(
        operationId = "modifierCategorie",
        summary = "Modifier une categorie",
        tags = { "Categorie" },
        responses = {
            @ApiResponse(responseCode = "200", description = "categorie modifié", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategorieDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CategoriesApi.PATH_MODIFIER_CATEGORIE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CategorieDTO> _modifierCategorie(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "CategorieUpdateDTO", description = "", required = true) @Valid @RequestBody CategorieUpdateDTO categorieUpdateDTO
    );


    String PATH_SUPPRIMER_CATEGORIE = "/categories/{id}";
    /**
     * DELETE /categories/{id} : Supprimer une categorie
     *
     * @param id  (required)
     * @return Supprimé (status code 204)
     */
    @Operation(
        operationId = "supprimerCategorie",
        summary = "Supprimer une categorie",
        tags = { "Categorie" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Supprimé")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CategoriesApi.PATH_SUPPRIMER_CATEGORIE
    )
    ResponseEntity<Void> _supprimerCategorie(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );

}
