/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package gestion_produit_crud.api;

import org.springframework.lang.Nullable;
import gestion_produit_crud.dto.ProduitAjoutDTO;
import gestion_produit_crud.dto.ProduitDTO;
import gestion_produit_crud.dto.ProduitUpdateDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-16T00:19:24.782253500Z[Atlantic/Reykjavik]", comments = "Generator version: 7.19.0")
@Validated
@Tag(name = "Produits", description = "the Produits API")
public interface ProduitsApi {

    String PATH_AFFICHER_PRODUIT_PAR_ID = "/produits/{id}";
    /**
     * GET /produits/{id} : Détail d’un produit
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "afficherProduitParId",
        summary = "Détail d’un produit",
        tags = { "Produits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProduitDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProduitsApi.PATH_AFFICHER_PRODUIT_PAR_ID,
        produces = { "application/json" }
    )
    ResponseEntity<ProduitDTO> _afficherProduitParId(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    String PATH_AJOUTER_PRODUIT = "/produits";
    /**
     * POST /produits : Créer un produit avec une image
     *
     * @param produitAjoutDTO  (optional)
     * @param image  (optional)
     * @return Produit créé (status code 201)
     */
    @Operation(
        operationId = "ajouterProduit",
        summary = "Créer un produit avec une image",
        tags = { "Produits" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Produit créé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProduitDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProduitsApi.PATH_AJOUTER_PRODUIT,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    ResponseEntity<ProduitDTO> _ajouterProduit(
        @Parameter(name = "produitAjoutDTO", description = "") @Valid @RequestPart(value = "produitAjoutDTO", required = false) ProduitAjoutDTO produitAjoutDTO,
        @Parameter(name = "image", description = "") @RequestPart(value = "image", required = false) MultipartFile image
    );


    String PATH_LISTR_TOUS_PRODUITS = "/produits";
    /**
     * GET /produits : Liste des produits
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "listrTousProduits",
        summary = "Liste des produits",
        tags = { "Produits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProduitDTO.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProduitsApi.PATH_LISTR_TOUS_PRODUITS,
        produces = { "application/json" }
    )
    ResponseEntity<List<ProduitDTO>> _listrTousProduits(
        
    );


    String PATH_MODIFIER_PRODUIT = "/produits/{id}";
    /**
     * PUT /produits/{id} : Modifier un produit avec une nouvelle image (optionnelle)
     *
     * @param id  (required)
     * @param produitUpdateDTO  (optional)
     * @param image  (optional)
     * @return Produit modifié (status code 200)
     */
    @Operation(
        operationId = "modifierProduit",
        summary = "Modifier un produit avec une nouvelle image (optionnelle)",
        tags = { "Produits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Produit modifié", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProduitDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProduitsApi.PATH_MODIFIER_PRODUIT,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    ResponseEntity<ProduitDTO> _modifierProduit(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "produitUpdateDTO", description = "") @Valid @RequestPart(value = "produitUpdateDTO", required = false) ProduitUpdateDTO produitUpdateDTO,
        @Parameter(name = "image", description = "") @RequestPart(value = "image", required = false) MultipartFile image
    );


    String PATH_SUPPRIMER_PRODUIT = "/produits/{id}";
    /**
     * DELETE /produits/{id} : Supprimer un produit
     *
     * @param id  (required)
     * @return Supprimé (status code 204)
     */
    @Operation(
        operationId = "supprimerProduit",
        summary = "Supprimer un produit",
        tags = { "Produits" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Supprimé")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ProduitsApi.PATH_SUPPRIMER_PRODUIT
    )
    ResponseEntity<Void> _supprimerProduit(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );

}
