/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package gestion_produit_crud.api;

import gestion_produit_crud.dto.UtilisateurDTO;
import gestion_produit_crud.dto.UtilisateurUpdateDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-16T00:19:24.782253500Z[Atlantic/Reykjavik]", comments = "Generator version: 7.19.0")
@Validated
@Tag(name = "Utilisateur", description = "the Utilisateur API")
public interface UtilisateurApi {

    String PATH_DELETE_UTILISATEUR = "/utilisateur/{id}";
    /**
     * DELETE /utilisateur/{id} : Supprime un utilisateur par ID
     *
     * @param id  (required)
     * @return Utilisateur supprimé avec succès (status code 204)
     *         or Utilisateur non trouvé (status code 404)
     */
    @Operation(
        operationId = "deleteUtilisateur",
        summary = "Supprime un utilisateur par ID",
        tags = { "Utilisateur" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Utilisateur supprimé avec succès"),
            @ApiResponse(responseCode = "404", description = "Utilisateur non trouvé")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = UtilisateurApi.PATH_DELETE_UTILISATEUR
    )
    ResponseEntity<Void> _deleteUtilisateur(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    String PATH_GET_UTILISATEUR_BY_ID = "/utilisateur/{id}";
    /**
     * GET /utilisateur/{id} : Affiche un utilisateur par ID
     *
     * @param id  (required)
     * @return Utilisateur trouvé (status code 200)
     *         or Utilisateur non trouvé (status code 404)
     */
    @Operation(
        operationId = "getUtilisateurById",
        summary = "Affiche un utilisateur par ID",
        tags = { "Utilisateur" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Utilisateur trouvé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UtilisateurDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "Utilisateur non trouvé")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UtilisateurApi.PATH_GET_UTILISATEUR_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<UtilisateurDTO> _getUtilisateurById(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    String PATH_LISTE_UTILISATEUR = "/utilisateur";
    /**
     * GET /utilisateur : Affiche tous les utilisateurs
     *
     * @return Liste des utilisateurs (status code 200)
     */
    @Operation(
        operationId = "listeUtilisateur",
        summary = "Affiche tous les utilisateurs",
        tags = { "Utilisateur" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Liste des utilisateurs", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UtilisateurDTO.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UtilisateurApi.PATH_LISTE_UTILISATEUR,
        produces = { "application/json" }
    )
    ResponseEntity<List<UtilisateurDTO>> _listeUtilisateur(
        
    );


    String PATH_MODIFIER_UTILISATEUR = "/utilisateur/{id}";
    /**
     * PUT /utilisateur/{id} : Modification de l&#39;utilisateur
     *
     * @param id  (required)
     * @param utilisateurUpdateDTO  (required)
     * @return Utilisateur modifié (status code 200)
     */
    @Operation(
        operationId = "modifierUtilisateur",
        summary = "Modification de l'utilisateur",
        tags = { "Utilisateur" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Utilisateur modifié", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UtilisateurDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UtilisateurApi.PATH_MODIFIER_UTILISATEUR,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<UtilisateurDTO> _modifierUtilisateur(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "UtilisateurUpdateDTO", description = "", required = true) @Valid @RequestBody UtilisateurUpdateDTO utilisateurUpdateDTO
    );

}
